name: "Performance Testing with K6"

on:
  push:
    branches:
      - main

jobs:
  performance-test:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Set up Node.js and install dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # or your preferred version
      
      - name: Install dependencies
        run: |
          npm install
          npm install -g newman  # if you are also running API tests
      
      # Run the server in the background
      - name: Run the application
        run: |
          nohup node server.js &
        
      # Wait a few seconds to allow the server to start
      - name: Wait for the server to start
        run: sleep 5

      # Install K6
      - name: Install K6
        run: |
          sudo apt update
          sudo apt install -y k6

      # Run K6 Performance Test
      - name: Run Performance Test
        run: |
          k6 run load_test.js
          
      # Optionally: Generate reports and save them as artifacts
      - name: Save performance test results
        uses: actions/upload-artifact@v3
        with:
          name: performance-results
          path: ./k6-results

